### ISSUE TITLE
recognition in real time

### ISSUE THREAD

**Issue by sundar19** [hasithsura/Environmental-Sound-Classification#1]
is it not possible to detect the environmental sounds in real time? like can I attach a microphone to detect it in real time? 
thanks.

**Comment by hasithsura** [comment]
Yes, you can use pyaudio to record audio using microphone at regular intervals.
It is better to maintain a thread that keeps writing real time audio to a buffer and another thread that extracts data from buffer and passes it to model for output.

**Comment by sundar19** [comment]
Is it not possible to have like an xml file , Like in case of OpenCV as example , and use it everytime? Like an inferred model after all the training? if I have to pass the data to the network in real time , will it cause any delay ?

**Comment by sundar19** [comment]
To clarify what I have understood is
1. You suggest to define a seperate function for pyaudio to get realtime data inside a buffer from mic and make it one thread
2. Then another function to proceed with getting the data from the previous buffer and load it inside the neural network and make it another thread.
So there is no need of librosa in my case , I can proceed with data coming from my pyaudio?

**Comment by hasithsura** [comment]
If you intend to use the model I trained, you can use torch.load to load the model for inference or you can also train your own model and save it using torch.save to load it later for inference. I think resnet 50 will cause a lot of delay. You can try resnet 34 or your own custom architecture and see how much delay it causes.
pyaudio is just for getting audio data from microphone. Librosa is still used to get spectrogram from audio and then the spectrogram is passed to the model for output.

**Comment by sundar19** [comment]
Ok I think you used pickle to save the model right? And I shld get the data from pyaudio and get a spectogram using librosa and pass it to the model , if I am right!

**Comment by hasithsura** [comment]
Yes

**Comment by sundar19** [comment]
Thank you so much. Sorry for a lot of questions as I am newbie to deep learning .

**Comment by hasithsura** [comment]
I have learned something too. I am happy to help.

**Comment by sundar19** [comment]
RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 4.00 GiB total capacity; 2.93 GiB already allocated; 5.80 MiB free; 2.94 GiB reserved in total by PyTorch)

Can you please help me with this?
how to rectify this error?
It is enough for me if I can train cough and sneeze datasets as of now? is it possible to train only those as my cuda runs out of memory?

**Comment by sundar19** [comment]
It is enough for me if I can train cough and sneeze datasets as of now? is it possible to train only those as my cuda runs out of memory?

**Comment by sundar19** [comment]
I have succesfully trained the model , but after restarting my jupyter I am unable to reload my trained model from disk using pickle? can you please help!
I get this error
EOFError: Ran out of input

**Comment by hasithsura** [comment]
I think it might be a problem with the size of pickle file. What is the size of pickle file? Can you paste the entire error message?

**Comment by sundar19** [comment]
EOFError                                  Traceback (most recent call last)
<ipython-input-23-b78c7154a486> in <module>
      2 import pickle
      3 with open('indtocat.pkl','rb') as f:
----> 4   indtocat = pickle.load(f)
      5 filename='/content/ESC-50-master/audio/1-116765-A-41.wav'
      6 spec=spec_to_image(get_melspectrogram_db(filename))

EOFError: Ran out of input
This is the error I get & my indtocat.pkl file size is 0 bytes? is the file saved correctly? 
Even if I have to retrain again how can I pickle it and save it?

**Comment by sundar19** [comment]
I even tried unpickling and loading but it was not helpful

**Comment by hasithsura** [comment]
indtocat.pkl should not be of size 0 bytes. It is basically a dictionary to map softmax output indices to categories. I think you should verify the pickle file and it's contents.

**Comment by sundar19** [comment]
Yeah I again trained and got a .pkl file and a .pth file . I copied those to a different path and wrote this code . But everytime it predicts wrong , may be I am using the wrong resnet? please help!

import IPython
import pickle
import librosa
import librosa.display
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision.models import resnet34

def spec_to_image(spec, eps=1e-6):
    mean = spec.mean()
    std = spec.std()
    spec_norm = (spec - mean) / (std + eps)
    spec_min, spec_max = spec_norm.min(), spec_norm.max()
    spec_scaled = 255 * (spec_norm - spec_min) / (spec_max - spec_min)
    spec_scaled = spec_scaled.astype(np.uint8)
    return spec_scaled

def get_melspectrogram_db(file_path, sr=None, n_fft=2048, hop_length=512, n_mels=128, fmin=20, fmax=8300, top_db=80):
  wav,sr = librosa.load(file_path,sr=sr)
  if wav.shape[0]<5*sr:
    wav=np.pad(wav,int(np.ceil((5*sr-wav.shape[0])/2)),mode='reflect')
  else:
    wav=wav[:5*sr]
  spec=librosa.feature.melspectrogram(wav, sr=sr, n_fft=n_fft,
              hop_length=hop_length,n_mels=n_mels,fmin=fmin,fmax=fmax)
  spec_db=librosa.power_to_db(spec,top_db=top_db)
  return spec_db

device=torch.device('cuda:0')

"""
with open('D:/Python36/ESC-50-master/esc50resnet.pth','rb') as s:
  resnet_model=torch.load(s)
"""

with open('D:/Python36/ESC-50-master/indtocat.pkl','rb') as f:
  indtocat = pickle.load(f)

resnet_model = resnet34(pretrained=True)
resnet_model.fc = nn.Linear(512,50)
resnet_model.conv1 = nn.Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
resnet_model = resnet_model.to(device)

filename='D:/Python36/ESC-50-master/audio/1-116765-A-41.wav'
spec=spec_to_image(get_melspectrogram_db(filename))
spec_t=torch.tensor(spec).to(device, dtype=torch.float32)
pr=resnet_model.forward(spec_t.reshape(1,1,*spec_t.shape))
ind = pr.argmax(dim=1).cpu().detach().numpy().ravel()[0]
print(indtocat[ind])
IPython.display.display(IPython.display.Audio(filename=filename))

**Comment by sundar19** [comment]
Thank you so much , now i learned to just pickle and import the model. Sorry again to ask a lot of questions!
Is there any way to seperately train only cough and sneeze 
Thanks!

**Comment by hasithsura** [comment]
It is fine. I learn from your questions too. You have to change last dense layer to have two units and dataset object to have two categories.

**Comment by sundar19** [comment]
something similar to this ?
train = df[df['category']='coughing','sneezing']
I can't understand from your code ,can you please pointout the output layer?

**Comment by hasithsura** [comment]
You have to pass num_cats=2 to the model. The dataset csv should contain paths to the audio files and category of each file. Number of categories will be picked up by the dataset object.

**Comment by sundar19** [comment]
to confirm,
num_cats = 2 means only two outputs cough and sneeze!
How do I categorize between train and valid? like 35 of cough and sneeze to train variable and 15 of cough and sneeze to validate! then do I have to change the number of nodes in the input layers too?

**Comment by hasithsura** [comment]
For that you can just have two seperate csv and create dataframes from them with train and valid as references.

**Comment by sundar19** [comment]
Thank you so much
